# -*- coding: utf-8 -*-
"""
Created on Tue Sep 12 17:21:06 2017

@author: Calil
"""

import numpy as np
import math

from sharc.simulation import Simulation
from sharc.parameters.parameters import Parameters
from sharc.station_factory import StationFactory

class SimulationFullDuplex(Simulation):
    """
    Implements the full duplex simulation
    """

    def __init__(self, parameters: Parameters):
        super().__init__(parameters)

        
    def snapshot(self, *args, **kwargs):
        pass


    def power_control(self):
        pass
    
        
    def calculate_sinr(self):
        """
        Calculates the downlink and uplink SINR for each UE and BS.
        Self-interference is considered
        """        
        pass

        
    def calculate_sinr_ext(self):
        """
        Calculates the SINR and INR for each UE and BS taking into
        account the interference that is generated by the other system into 
        IMT system.
        """
        pass
        
        
    def calculate_external_interference(self):
        """
        Calculates interference that IMT system generates on other system
        """
        pass
        
        
    def collect_results(self, write_to_file: bool, snapshot_number: int):
        pass

